global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "demo-applications"
    static_configs:
      - targets:
          - "demo-app-1:9273"
          - "demo-app-2:9273"
          - "demo-app-3:9273"
          - "demo-app-4:9273"
    scrape_interval: 15s
    metrics_path: /metrics